// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/32f0a90dab26f70b206407ac24d4d622d0f0f408/debug/debug.d.ts
declare module "debug" {

    function d(namespace: string): d.Debugger;

    module d {
        export var log: Function;

        function enable(namespaces: string): void;
        function disable(): void;

        function enabled(namespace: string): boolean;

        export interface Debugger {
            (formatter: any, ...args: any[]): void;

            enabled:   boolean;
            log:       Function;
            namespace: string;
        }
    }

    export = d;

}